### ISSUE TITLE
Define APIs for tables

### ISSUE THREAD

**Issue by kaihendry** [unee-t/enterprise-rest-api#1]
For example /persons maps to the **persons** table.

https://media.dev.unee-t.com/2019-04-04/tables.txt

What are the others?

**Comment by franck-boullier** [comment]
# The Tables:

As of version 1.4.0 of the Unee-T Enterprise database schema, the tables you need to update with the Unee-T API will be the following:
- `external_persons`
- `external_property_addresses`
- `external_property_groups_areas`
- `external_property_level_1_building`
- `external_property_level_2_units`
- `external_property_level_3_rooms`
- `external_map_user_permissions_unit_level_1`
- `external_map_user_permissions_unit_level_2`
- `external_map_user_permissions_unit_level_3`
- `external_user_types`

# How to know the schema version of the database:

Look at the latest record in the table `db_schema_version` in the database

**Comment by franck-boullier** [comment]
the schema for the Unee-T Enterprise database has been updated to v1.4.0 in the DEV/Staging, DEMO and PROD environments.
The tables:
- `external_persons`
- `external_property_level_1_building`
- `external_property_level_2_units`
- `external_property_level_3_rooms`
Are now available there and the schema should be the final one ---> you could start working in the Unee-T Enterprise API for these
I'll create the rest of the tables that shall be editable with the Unee-T Enterprise API in the DB schema v1.5.0 that I plan to release later

**Comment by franck-boullier** [comment]
It's better, more manageable to tackle each of these 1 by 1.
See #2, #3 , #4, #5, #6, #7 for more details on each of the things that we need to be able to modify via the UNTE APIs
Closing this
