### ISSUE TITLE
API to check the list of possible unit types

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/enterprise-rest-api#8]
One of the requirement of #3 is that the 3rd party uses a valid Unit Type when a unit is created or modified.

This document the API to retrieve the list of Active Unit Type

#  How it should work:

- 3rd party API call a UNTE Endpoint

### Input:

`active`

### Output:

The list of active unit types
- Designation (Office, Hotel, Flat, Room, etc...)

### The SQL query to retrieve the list of Unit Types:

Below is the query to list this in the UNTE Database

```
SELECT `designation` 
FROM `ut_unit_types`
WHERE `is_obsolete` = 0
;
```
### Input:

`all`

### Output:

The list of ALL unit types:
- Unit type designation (Office, Hotel, Flat, Room, etc...)
- 1 if this is INACTIVE (obsolete) or 0 if this is ACTIVE

### The SQL query to retrieve the list of Unit Types:

Below is the query to list this in the UNTE Database

```
SELECT `designation` 
  , `is_obsolete`
FROM `ut_unit_types`
;
```

**Comment by kaihendry** [comment]
Isn't the active/all a bit over engineered? Why not just return the current list like country codes?

**Comment by kaihendry** [comment]
Documented in Postman https://documenter.getpostman.com/view/3704379/SVSEtB4z though atm there is an odd sync bug giving the wrong request name of "List country codes Copy"

**Comment by franck-boullier** [comment]
@kaihendry the current implementation is different from what was specified [here](https://github.com/unee-t/enterprise-rest-api/issues/8#issue-465579146).

Can you please describe what you have done so I can understand and test it?
And no, the current description in postman does NOT help me understand what you were trying to implement (are you returning all the unit types or just the active ones?)

**Comment by kaihendry** [comment]
* https://eapi.dev.unee-t.com/unittypes?all
* https://eapi.dev.unee-t.com/unittypes?active which is the same as https://eapi.dev.unee-t.com/unittypes

**Comment by franck-boullier** [comment]
> https://eapi.dev.unee-t.com/unittypes?all

This one is missing the status of the Unit Type record (active or not) Is this complex to implement @kaihendry ?

**Comment by kaihendry** [comment]
Introduced the inactive mapping in https://github.com/unee-t/enterprise-rest-api/commit/af76e490cd8c79391cfa45f71fa9bf4d42aadf7a

**Comment by franck-boullier** [comment]
Thanks @kaihendry!

Can you please reploy this to the DEMO and PROD environment and close this issue when it's done?

**Comment by kaihendry** [comment]
* https://eapi.dev.unee-t.com/unittypes?all
* https://eapi.demo.unee-t.com/unittypes?all
* https://eapi.unee-t.com/unittypes?all
