### ISSUE TITLE
API to retrieve the list of country codes

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/enterprise-rest-api#9]
One of the requirement of #3 is that the 3rd party uses a valid Country code when a unit is created or modified.

This document the API to retrieve the list of possible country codes.

#  How it should work:

- 3rd party API call a UNTE Endpoint

### Input:

not applicable (no input needed)

### Output:

The list of countries and country codes
- Country  Code (AU, SG, FR, ...)
- Country Name (Australia, Singapore, France, ...)

### The SQL query to retrieve the list of country codes:

Below is the query to list this in the UNTE Database

```
SELECT `country_code` 
  , `country_name`
FROM `property_groups_countries`
;
```

**Comment by kaihendry** [comment]
Documented on https://documenter.getpostman.com/view/3704379/SVSEtB4z?version=latest#6962ca57-4e7e-4ebc-809b-5034ec0eb004

**Comment by franck-boullier** [comment]
Need to be verified before it's closed

**Comment by franck-boullier** [comment]
This works as intended and has been [documented](https://documentation.unee-t.com/2019/07/11/api-check-the-list-of-valid-country-codes/).

@kaihendry can you deploy this in the DEMO and PROD environment and then close the issue

Thanks!

**Comment by kaihendry** [comment]
Latest state has been deployed to:

* DEV https://eapi.dev.unee-t.com/countries
* DEMO https://eapi.demo.unee-t.com/countries
* PROD https://eapi.unee-t.com/countries
